// lib/data.ts
import { Product } from '@/types';

// Helper function to create slugs
const createSlug = (name: string) => {
  return name
    .toLowerCase()
    .replace(/ /g, '-')
    .replace(/[^\w-]+/g, '');
};

// This data is now conformed to the 'Product' type from 'types/index.ts'
export const products: Product[] = [
  // Panadería
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    name: 'Pan de Centeno y Nueces',
    description: 'Elaborado con harina de centeno integral, masa madre y nueces. Miga densa y aromática con una corteza crujiente.',
    price: 18,
    discount_price: null,
    ingredients: ['Harina de centeno integral', 'Masa madre', 'Nueces', 'Agua', 'Sal'],
    image_src: '/images/producto-pan-centeno-nueces.jpg',
    image_alt: 'Pan de Centeno y Nueces',
    category_id: 'panaderia',
    stock: 20,
    slug: 'pan-de-centeno-y-nueces',
    isFeatured: true,
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14',
    name: 'Ciabatta con Aceitunas',
    description: 'Pan de estilo italiano con corteza crujiente, miga aireada y un toque salado de aceitunas Kalamata.',
    price: 15,
    discount_price: null,
    ingredients: ['Harina de trigo', 'Aceitunas Kalamata', 'Levadura', 'Agua', 'Sal', 'Aceite de oliva'],
    image_src: '/images/producto-ciabatta-aceitunas.jpg',
    image_alt: 'Ciabatta con Aceitunas',
    category_id: 'panaderia',
    stock: 18,
    slug: 'ciabatta-con-aceitunas',
    isFeatured: true,
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15',
    name: 'Croissant de Mantequilla',
    description: 'Clásico francés hojaldrado a la perfección, con un exterior dorado y un interior suave y mantecoso.',
    price: 8,
    discount_price: null,
    ingredients: ['Harina de trigo', 'Mantequilla', 'Leche', 'Azúcar', 'Levadura', 'Sal'],
    image_src: '/images/producto-croissant-mantequilla.jpg', // Note: Placeholder might not match
    image_alt: 'Croissant de Mantequilla',
    category_id: 'panaderia',
    stock: 30,
    slug: 'croissant-de-mantequilla',
    isFeatured: true,
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a17',
    name: 'Pan de Queso',
    description: 'Pequeños bocados de felicidad, crujientes por fuera y elásticos por dentro, con un intenso sabor a queso.',
    price: 7,
    discount_price: null,
    ingredients: ['Almidón de yuca', 'Queso parmesano', 'Huevo', 'Leche', 'Mantequilla'],
    image_src: '/images/producto-pan-queso.jpg',
    image_alt: 'Pan de Queso',
    category_id: 'panaderia',
    stock: 40,
    slug: 'pan-de-queso',
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a19',
    name: 'Focaccia con Romero y Sal Marina',
    description: 'Pan plano esponjoso, rociado con aceite de oliva, romero fresco y cristales de sal marina.',
    price: 20,
    discount_price: 17.50,
    ingredients: ['Harina de trigo', 'Aceite de oliva', 'Romero fresco', 'Sal marina', 'Levadura'],
    image_src: '/images/producto-focaccia-romero.jpg',
    image_alt: 'Focaccia con Romero y Sal Marina',
    category_id: 'panaderia',
    stock: 12,
    slug: 'focaccia-con-romero-y-sal-marina',
  },
  // Tortas
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
    name: 'Torta de Chocolate Intenso',
    description: 'Capas de bizcocho húmedo de chocolate, rellenas y cubiertas con una rica ganache de chocolate negro.',
    price: 45,
    discount_price: 39.99,
    ingredients: ['Chocolate negro', 'Harina de trigo', 'Azúcar', 'Huevos', 'Mantequilla', 'Cacao en polvo'],
    image_src: '/images/producto-torta-chocolate-intenso.jpg',
    image_alt: 'Torta de Chocolate',
    category_id: 'tortas',
    stock: 15,
    slug: 'torta-de-chocolate-intenso',
    isFeatured: true,
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a20',
    name: 'Tarta de Manzana Clásica',
    description: 'Base de masa quebrada casera con un relleno generoso de manzanas frescas especiadas con canela.',
    price: 35,
    discount_price: null,
    ingredients: ['Manzanas', 'Harina de trigo', 'Mantequilla', 'Azúcar', 'Canela', 'Limón'],
    image_src: '/images/producto-tarta-manzana-clasica.jpg',
    image_alt: 'Tarta de Manzana Clásica',
    category_id: 'tortas',
    stock: 10,
    slug: 'tarta-de-manzana-clasica',
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    name: 'Torta Red Velvet',
    description: 'Bizcocho de terciopelo rojo, suave y húmedo, coronado con un generoso frosting de queso crema.',
    price: 50,
    discount_price: 44.99,
    ingredients: ['Harina de trigo', 'Azúcar', 'Buttermilk', 'Queso crema', 'Mantequilla', 'Colorante rojo'],
    image_src: '/images/producto-torta-red-velvet.jpg',
    image_alt: 'Torta Red Velvet',
    category_id: 'tortas',
    stock: 20,
    slug: 'torta-red-velvet',
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a23',
    name: 'Cheesecake de Fresa',
    description: 'Cremoso cheesecake sobre una base de galleta, cubierto con una capa de mermelada de fresas frescas.',
    price: 40,
    discount_price: null,
    ingredients: ['Queso crema', 'Galletas tipo Graham', 'Fresas', 'Azúcar', 'Nata', 'Mantequilla'],
    image_src: '/images/producto-cheesecake-fresa.jpg', // Placeholder
    image_alt: 'Cheesecake de Fresa',
    category_id: 'tortas',
    stock: 15,
    slug: 'cheesecake-de-fresa',
  },
  // Pastelería
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a16',
    name: 'Muffin de Arándanos',
    description: 'Suave, esponjoso y repleto de arándanos frescos que estallan en sabor con cada bocado.',
    price: 10,
    discount_price: 8.50,
    ingredients: ['Harina de trigo', 'Arándanos', 'Azúcar', 'Huevo', 'Leche', 'Mantequilla'],
    image_src: '/images/producto-muffin-arandanos.jpg',
    image_alt: 'Muffin de Arándanos',
    category_id: 'pasteleria',
    stock: 22,
    slug: 'muffin-de-arandanos',
    isFeatured: true,
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a18',
    name: 'Galletas de Avena y Pasas',
    description: 'La combinación perfecta de saludable y delicioso, con avena integral, pasas y un toque de canela.',
    price: 9,
    discount_price: null,
    ingredients: ['Avena', 'Pasas', 'Harina integral', 'Azúcar moreno', 'Huevo', 'Canela'],
    image_src: '/images/producto-galletas-avena-pasas.jpg',
    image_alt: 'Galletas de Avena y Pasas',
    category_id: 'pasteleria',
    stock: 35,
    slug: 'galletas-de-avena-y-pasas',
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a24',
    name: 'Palmera de Hojaldre',
    description: 'Crujiente y caramelizada, una clásica palmera de hojaldre perfecta para una merienda ligera.',
    price: 6,
    discount_price: null,
    ingredients: ['Masa de hojaldre', 'Azúcar', 'Mantequilla'],
    image_src: '/images/producto-palmera-hojaldre.jpg', // Placeholder
    image_alt: 'Palmera de Hojaldre',
    category_id: 'pasteleria',
    stock: 40,
    slug: 'palmera-de-hojaldre',
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a25',
    name: 'Macarons Surtidos (Caja de 6)',
    description: 'Una selección de 6 macarons de diferentes sabores: frambuesa, pistacho, chocolate, vainilla, limón y café.',
    price: 25,
    discount_price: null,
    ingredients: ['Almendra molida', 'Clara de huevo', 'Azúcar glas', 'Rellenos variados'],
    image_src: '/images/producto-macarons-surtidos.jpg', // Placeholder
    image_alt: 'Macarons Surtidos',
    category_id: 'pasteleria',
    stock: 20,
    slug: 'macarons-surtidos',
  },
  // Postres
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13',
    name: 'Rollos de Canela Glaseados',
    description: 'Suaves y esponjosos, rellenos de canela y azúcar moreno, coronados con un glaseado de queso crema.',
    price: 12,
    discount_price: null,
    ingredients: ['Harina de trigo', 'Canela', 'Azúcar moreno', 'Queso crema', 'Mantequilla'],
    image_src: '/images/producto-rollos-canela-glaseados.jpg',
    image_alt: 'Rollos de Canela',
    category_id: 'postres',
    stock: 25,
    slug: 'rollos-de-canela-glaseados',
    isFeatured: true,
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a21',
    name: 'Brownie de Chocolate y Nuez',
    description: 'Intensamente chocolatoso, con una textura fudgy por dentro y una capa crujiente por fuera.',
    price: 15,
    discount_price: null,
    ingredients: ['Chocolate', 'Nueces', 'Mantequilla', 'Harina', 'Azúcar', 'Huevos'],
    image_src: '/images/producto-brownie-chocolate-nuez.jpg',
    image_alt: 'Brownie de Chocolate y Nuez',
    category_id: 'postres',
    stock: 18,
    slug: 'brownie-de-chocolate-y-nuez',
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a26',
    name: 'Tiramisú Clásico',
    description: 'Capas de bizcochos de soletilla empapados en café, intercaladas con una crema de mascarpone y cacao.',
    price: 18,
    discount_price: null,
    ingredients: ['Queso mascarpone', 'Bizcochos de soletilla', 'Café', 'Huevo', 'Cacao en polvo'],
    image_src: '/images/producto-tiramisu-clasico.jpg', // Placeholder
    image_alt: 'Tiramisú Clásico',
    category_id: 'postres',
    stock: 15,
    slug: 'tiramisu-clasico',
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a27',
    name: 'Panna Cotta con Frutos Rojos',
    description: 'Postre italiano sedoso y delicado, servido con una compota casera de frutos rojos.',
    price: 16,
    discount_price: null,
    ingredients: ['Nata', 'Azúcar', 'Gelatina', 'Frutos rojos', 'Vainilla'],
    image_src: '/images/producto-panna-cotta-frutos-rojos.jpg', // Placeholder
    image_alt: 'Panna Cotta con Frutos Rojos',
    category_id: 'postres',
    stock: 20,
    slug: 'panna-cotta-frutos-rojos',
  },
].map(p => ({ ...p, slug: p.slug || createSlug(p.name) })); // Ensure all products have a slug
